configName: google.yml
# To switch on the Firebug plugin
firebug: true
firebug-version: 2.0.7
# Browser for launching tests
browser: firefox
#Timeout
Timeout: 30


#For proxy
enableProxy: true
proxyPort: 7000


#FRONTEND TESTS
isTest: false

#mvn clean test -DsuiteFile=src/test/resources/suite/google.xml