configName: live
# To switch on the Firebug plugin
firebug: false
firebug-version: 2.0.7
# Browser for launching tests
browser: chrome
#Timeout
Timeout: 10


#Dimension

dimensionW:
dimensionH:

#For proxy
enableProxy: true
proxyPort: 7000


#FRONTEND TESTS
isTest: false

#mvn clean test -DsuiteFile=src/test/resources/suite/google.xml