configName: live

# To switch on the Firebug plugin
firebug: false
firebug-version: 2.0.7
# Browser for launching tests
remote: false
browser: chrome
hubAddress: http://172.27.5.65:4444/wd/hub
Timeout: 10


#MOBILE SETTING
isMobile: false
mobileBrowser: browser
mobilePlatform: android
mobilePlatformVersion: 7.0
mobileDeviceName: phone
udid: emulator-5554
appiumAddress: http://127.0.0.1:4723/wd/hub


#Dimension
dimensionW: 1920
dimensionH: 1080

#For proxy
enableProxy: true
#Have to up it on remote host(s)
remoteProxyHost: 172.27.5.65
proxyPort: 7000


#FRONTEND TESTS
isTest: false

#mvn clean test -DsuiteFile=src/test/resources/suite/google.xml